# Generated by Django 5.0.6 on 2024-07-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_product_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
